version: "3"
x-service-defaults:
  &service-defaults
  build:
    context: .
  volumes:
    - .:/opt
    - "build:/opt/_build"
    - "deps:/opt/deps"
  ports:
    - "4000:4000"
  depends_on:
    - db

services:
  web:
    <<: *service-defaults
    environment:
      - DATABASE_HOST=db
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=to_do

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5403:5432"
    networks:
      default:
        aliases:
          - db

volumes:
  build:
  deps:
